INEEJI/ineeji-api-references

swagger.yaml
version: "1.0.7" -> version: "1.0.8"
=> [Version up] 문서에 업데이트가 되지 않아 버전업합니다. 

swagger.yaml
=> 문서 업데이트  check 

swagger.yaml
https://github.com/INEEJI/ineeji-api-references/pull/6 재반영
=> [CSI-127 이 반영되지 않아 재반영]

swagger.yaml
/v1/list_model 에 parameter 추가 (is_classification) 입니다. 
is_classification : True 인 경우 (classification)
is_classification : False 인 경우 (Regression) 
추가 사유.
1. Model 의 주요 정보임. 
2. 모델의 유형에 따라 FE 학습결과 페이지가 달라서 필요 정보임. 
3. 기존 DB 의 schema 가 is_classification 의 경우 int 형이지만 [DROPBOX API ](https://www.dropbox.com/developers/documentation/http/documentation#users-get_account) 참고하여, Bool 값으로 변환하여 보냄.
=> list_model 에 parameter 추가 (is_classification)

swagger.yaml
어제 추가한 API가 웹에 정상적으로 게시되지 않음
확인해보니 query parameter(offset, limit)가 들어간 부분에 파라메터 선언이 누락되어 추가하였습니다.
=> Add path parameters for xai_result pagination

swagger.yaml
이 PR은 자동으로 생성되는 모델명을 수정하기 위한 API spec을 정의합니다. (/rename_model/{model_id})
=> [CSI-276] Add rename_model API

swagger.yaml
1. 부분 업데이트이므로 post -> patch 로 수정
2. Bad Request 에 대한 응답 추가
=> [CSI-276] rename_model API 업데이트 

swagger.yaml
resp_bad_request:  resp_unauthorized: 의 에러에 대한 응답 시, key name 을 backend 에 정의되어 있는 message -> detail 로 수정
=> response message 의 key  수정 ( message -> detail  )

swagger.yaml
모델을 삭제할 수 있는 기능을 개발하기 위해 /delete_model API spec을 정의합니다.
=> [CSI-332] Add /v1/delete_model/{model_id}

swagger.yaml
모델 취소에 대한 API 정의입니다.  
/v1/cancel_model/{model_id}
CSI-365
=> [CSI-365] 모델 취소에 대한 API 정의 /v1/cancel_model/{model_id}

swagger.yaml
사용자별 조회가능한 symbol 을 return 하는 API 추가
/v2/economy/get_symbol_info
- 사용자별 테이블에 등록된 사용자일 경우, 해당 symbol 을 리턴합니다.
- 사용자별 테이블에 등록된 사용자일 경우, 모든 사용 가능한 symbol 을 리턴합니다.
EI2-32
=> [EI2-32] 사용자별 조회가능 symbol 을 return 하는 API(get_symbol_info) 추가

swagger.yaml
symbol, horizon 으로 조회 가능한 global feature importance API 를 정의합니다. 
/v2/economy/global_exp/{symbol}?horizons={number}
EI2-41
=> [EI2-41] global feature importance API 추가

swagger.yaml
/v2/economy 관련 최신 내용으로 apiary 업데이트 
-   /v2/economy/get_symbol_info
-  /v2/economy/prediction/{symbol}
- /v2/economy/rawdata_v2/{symbol}
EI2-114
=> [EI2-114] /v2/economy api 업데이트

swagger.yaml
index v2 api 를 업데이트 합니다.
v2/economy/get_predicton_metric
v2/economy/local_attribution_bydate 
EI2-114
=> [EI2-114] index v2 api 업데이트 

swagger.yaml
index v2 api 업데이트 입니다.
EI2-114
=> [EI2-114] index v2 api 업데이트

swagger.yaml
/api/v1/delete_model/{model_id} [ DELETE ] API 문서 업데이트 합니다.
- [ O ] post method -> delete method로 변경
- [ O ] summary 수정
ES2-193
=> update: HTTP method of the model delete API

swagger.yaml
- [ O ] dataset_list/{user_id} API [ post ] : 
- [ O ] edit_data/{user_id} API [ patch ] : dataset 수정하기
- [ O ] delete_data/{user_id} API [ delete ]: dataset 삭제하기
- [ O ] get_model_option API [ post ] : model 생성 요청하기
ES2-192
=> [ES2-192] 실사용 중인 누락 - dataset 연관 API 추가

swagger.yaml
1. train model API 추가
- api/train_model
2. model_list API 업데이트
- api/model_list 
ES2-239
=> [ES2-239] 재학습 연관 API 추가

swagger.yaml
[bnd PR](https://github.com/INEEJI/csi-cloudfnt-backend/pull/269)에 맞추어 Apiary update하는 PR입니다.
=> retrain을 위하여 ds_id를 추가

swagger.yaml
- 변경사항
- ds_id의 descrition 변경
- 추가사항
- 추가된 이전 모델 정보 (prev_model_id, prev_model_name)
=> Add previous model information
